# extlinux.conf - Initial Arcadia Linux Boot Configuration
# This file will be automatically updated by kernel update hooks

default arcadia
timeout 30
menu title Arcadia Linux Boot Menu

label arcadia
    menu label Arcadia Linux (Initial)
    linux /Image-initramfs-radxa-zero3w.bin
    fdt /rk3566-radxa-zero-3w.dtb
    append rootwait rw console=ttyS2,1500000 console=tty1 earlycon=uart8250,mmio32,0xfe660000 consoleblank=0 video=HDMI-A-1:1024x768@75 swiotlb=131072 splash quiet vt.global_cursor_default=0 loglevel=1 ${extraargs} ${extraboardargs}
