# Modern mainline u-boot for Radxa Zero 3W (Rockchip RK3566).
#
# v2024.10 had its libfdt.i_shipped generated by SWIG 4.0.x which is
# binary-incompatible with wrynose 6.0's SWIG 4.4.1 (mismatched
# SWIG_Python_AppendOutput arity). Bumping to v2026.01 picks up the
# regenerated wrap.c that matches wrynose's host swig.
#
# What we do here:
#   - Build u-boot v2026.01 from source.denx.de/u-boot using the
#     radxa-zero-3-rk3566_defconfig (CONFIG_ROCKCHIP_RK3568=y;
#     same SoC binary tree as rk3566).
#   - Vendor radxa/rkbin develop-v${PV} for BL31 + DDR init blobs;
#     second SCM with destsuffix=rkbin.
#   - In do_compile:prepend, copy bin/rk35/rk3568_bl31_v*.elf and
#     rk3566_ddr_*.bin + tools/ into ${S} so mainline u-boot's
#     make_fit_atf.sh pipeline finds them.

require recipes-bsp/u-boot/u-boot-common.inc
require recipes-bsp/u-boot/u-boot.inc

SUMMARY = "U-Boot bootloader for Radxa Zero 3W (Rockchip RK3566)"
DESCRIPTION = "Mainline u-boot v2026.01 with radxa-zero-3-rk3566_defconfig; \
pairs with radxa/rkbin develop-v${PV} for BL31 + DDR init blobs. \
Output is u-boot.itb + u-boot-rockchip.bin, the rockchip multi-stage \
SPL/ITB pair consumed by idbloader packing during image generation."

SRC_URI = "git://source.denx.de/u-boot/u-boot.git;protocol=https;branch=master;tag=v${PV} \
           git://github.com/radxa/rkbin.git;protocol=https;branch=develop-v${PV};name=rkbin;destsuffix=rkbin"

# Multiple SCMs in SRC_URI require SRCREV_FORMAT to disambiguate them.
# u-boot itself is the first SCM (=>SRCREV); the second is named 'rkbin'.
SRCREV_FORMAT = "_rkbin"

# u-boot v2026.01 tag points to commit 168e3fe6d65a99b4b93c3803f74889adacd908e9
# (verified against source.denx.de/u-boot mirror via git ls-remote).
SRCREV = "168e3fe6d65a99b4b93c3803f74889adacd908e9"

# radxa/rkbin develop-v2026.01 HEAD = 02931bbd3f9756cbad556d73f6447b9a5b3fc240;
# ships bin/rk35/rk3566_ddr_1056MHz_v1.25.bin and the rk3568 bl31 cpu3 v1.01.elf
# (rockchip rk3568 vendor firmware which integrates well as the rk3566
# family ATF entry point).
SRCREV_rkbin = "02931bbd3f9756cbad556d73f6447b9a5b3fc240"

PE = "1"

PROVIDES += "virtual/bootloader u-boot"

# --- Modern U-Boot configuration flow (wrynose 6.0) ---
UBOOT_CONFIG ??= "radxa-zero3w"
UBOOT_CONFIG[radxa-zero3w] = "radxa-zero-3-rk3566_defconfig"
UBOOT_CONFIG_BINARY[radxa-zero3w] = "u-boot-rockchip.bin"
UBOOT_CONFIG_IMAGE_FSTYPES[radxa-zero3w] = "ext4 fit"

UBOOT_SUFFIX ?= "bin"
PACKAGE_ARCH = "${MACHINE_ARCH}"

# mkeficapsule.c (u-boot host tool) requires libgnutls headers on the
# host build. wrynose 6.0's u-boot-tools inherit gnutls-native via the
# upstream DEPENDS list, but the recipe-specific radxa-zero3 path bypasses
# u-boot-common.inc's DEFAULT_PREFERENCE setup -- add it explicitly.
DEPENDS += "gnutls-native"

# --- Rockchip multi-stage artefact staging ---------------------------------
RK = "${UNPACKDIR}/rkbin"

# Required by the rockchip make_fit_atf.sh pre-processor in SPL build:
# BL31 = arm-trusted-firmware (.elf), ROCKCHIP_TPL = DDR init (.bin).
# We grab the rk3568 bl31 (works as rk3566 family firmware) and the
# 1056 MHz DDR binary (radxa-zero3 pred spec).
# u-boot v2026.01's pylibfdt libfdt_wrap.c is regenerated by swig 4.4
# at build time and matches the host gcc ABI exactly. No manual patch
# needed.
do_compile:prepend() {
    # Match the radxa-zero3 radxa-rkbin fork layout: bl31 cpu3 v1.01
    # plus rk3566_ddr_1056MHz_v1.25 (the OEM-pinned variant).
    if [ -f ${RK}/bin/rk35/rk3568_bl31_cpu3_v1.01.elf ]; then
        cp -a ${RK}/bin/rk35/rk3568_bl31_cpu3_v1.01.elf  ${S}/
    fi
    if [ -f ${RK}/bin/rk35/rk3566_ddr_1056MHz_v1.25.bin ]; then
        cp -a ${RK}/bin/rk35/rk3566_ddr_1056MHz_v1.25.bin ${S}/
    fi
    if [ -d ${RK}/tools ]; then
        cp -a ${RK}/tools ${S}/
    fi
}

do_deploy:append() {
    install -d ${DEPLOYDIR}
    # New-style Rockchip binaries (preferred by mainline tooling)
    install -m 755 ${B}/u-boot.itb          ${DEPLOYDIR}/u-boot.itb
    install -m 755 ${B}/u-boot-rockchip.bin ${DEPLOYDIR}/u-boot.bin
}

COMPATIBLE_MACHINE = "radxa-zero3w"
